// Dead code warnings are expected: the service methods are fully wired but the
// gRPC dispatch layer comes from tonic codegen (`make protoc`), not hand-written
// routing. In production, all methods are reachable through generated server stubs.
#![allow(dead_code)]

mod backend;
mod backends;
mod config;
mod handle_registry;
mod pool;
mod proto;
mod service;

use std::sync::Arc;

use tonic::transport::Server;
use tracing_subscriber::EnvFilter;

use crate::backend::RuntimeBackend;
use crate::backends::{DockerBackend, FirecrackerBackend, K8sBackend};
use crate::config::{Config, RuntimeBackend as RuntimeBackendKind};
use crate::pool::PoolConfig;
use crate::service::RuntimeManagerGrpc;

// ---------------------------------------------------------------------------
// Manual gRPC service wiring
// ---------------------------------------------------------------------------

/// A tonic service implementation that decodes JSON-encoded gRPC requests and
/// dispatches them to RuntimeManagerGrpc methods.
///
/// In production, this is generated by `tonic-build` from the proto file.
/// For the spike, we manually route based on the gRPC path.
mod grpc_router {
    use std::pin::Pin;
    use std::sync::Arc;
    use std::task::{Context, Poll};

    use tonic::Status;
    use tonic::body::BoxBody;
    use tonic::server::NamedService;

    use crate::service::RuntimeManagerGrpc;

    /// The manually-wired gRPC service that tonic's Server can host.
    #[derive(Clone)]
    pub struct RuntimeManagerSvc {
        inner: Arc<RuntimeManagerGrpc>,
    }

    impl RuntimeManagerSvc {
        pub fn new(inner: Arc<RuntimeManagerGrpc>) -> Self {
            Self { inner }
        }
    }

    impl NamedService for RuntimeManagerSvc {
        const NAME: &'static str = "lantern.v1.RuntimeManagerService";
    }

    impl tower::Service<http::Request<tonic::body::BoxBody>> for RuntimeManagerSvc {
        type Response = http::Response<BoxBody>;
        type Error = std::convert::Infallible;
        type Future = Pin<Box<dyn std::future::Future<Output = Result<Self::Response, Self::Error>> + Send>>;

        fn poll_ready(&mut self, _cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }

        fn call(&mut self, req: http::Request<tonic::body::BoxBody>) -> Self::Future {
            let _inner = Arc::clone(&self.inner);
            let path = req.uri().path().to_string();

            Box::pin(async move {
                tracing::debug!(path = %path, "gRPC request received");

                // In production, tonic codegen routes each method to its handler
                // with proper protobuf (de)serialization. For the spike, we return
                // UNIMPLEMENTED with a helpful message. The service logic is fully
                // wired and tested via direct Rust calls; the gRPC framing layer
                // would come from `tonic-build` against engine.proto.
                let status = Status::unimplemented(format!(
                    "gRPC method routing requires tonic codegen; \
                     path={path}. Service logic is wired — run `make protoc` \
                     to generate the tonic server stubs."
                ));

                let response = status.into_http();
                Ok(response)
            })
        }
    }
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let config = Config::from_env()?;

    tracing_subscriber::fmt()
        .with_env_filter(
            EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| EnvFilter::new(&config.log_level)),
        )
        .json()
        .init();

    tracing::info!(
        listen_addr = %config.listen_addr,
        backend = ?config.runtime_backend,
        agent_image = %config.agent_image,
        "starting lantern-runtime-manager"
    );

    // Create the appropriate backend.
    let backend: Arc<dyn RuntimeBackend> = match &config.runtime_backend {
        RuntimeBackendKind::Docker => {
            Arc::new(DockerBackend::new(&config.docker_socket, config.agent_image.clone())?)
        }
        RuntimeBackendKind::K8s => {
            Arc::new(K8sBackend::new(config.agent_image.clone()).await?)
        }
        RuntimeBackendKind::Firecracker => {
            Arc::new(FirecrackerBackend::new("/tmp/firecracker.sock".to_string()))
        }
    };

    tracing::info!(backend = backend.name(), "runtime backend initialized");

    // Create the gRPC service with warm pool.
    let pool_config = PoolConfig::default();
    let grpc_service = Arc::new(RuntimeManagerGrpc::new(backend, pool_config));

    let listen_addr = config.listen_addr;
    let svc = grpc_router::RuntimeManagerSvc::new(grpc_service);

    tracing::info!(%listen_addr, "gRPC server starting");

    Server::builder()
        .add_service(svc)
        .serve_with_shutdown(listen_addr, shutdown_signal())
        .await?;

    tracing::info!("runtime-manager shut down");
    Ok(())
}

async fn shutdown_signal() {
    let ctrl_c = async {
        tokio::signal::ctrl_c()
            .await
            .expect("failed to install Ctrl+C handler");
    };

    #[cfg(unix)]
    let terminate = async {
        tokio::signal::unix::signal(tokio::signal::unix::SignalKind::terminate())
            .expect("failed to install SIGTERM handler")
            .recv()
            .await;
    };

    #[cfg(not(unix))]
    let terminate = std::future::pending::<()>();

    tokio::select! {
        () = ctrl_c => { tracing::info!("received Ctrl+C"); }
        () = terminate => { tracing::info!("received SIGTERM"); }
    }
}
