//! Proto types for the runtime manager.
//!
//! Two layers live here:
//!
//! 1. **Wire types** under [`pb`] — generated by `tonic-build` from
//!    `packages/proto/lantern/v1/runtime.proto` at compile time (see
//!    `build.rs`). These are the on-the-wire `SpawnRequest`,
//!    `StopRequest`, `LogLine`, etc. that the gRPC server exposes.
//!
//! 2. **Internal types** at the module root — the hand-rolled
//!    `ScheduleRequest`, `RuntimeEvent`, `IsolationClass`, ... that
//!    the warm pool, handle registry, and backend implementations
//!    (`backends/docker.rs`, `firecracker.rs`, `k8s.rs`) consume.
//!    These are richer than the wire-level `SpawnRequest` because
//!    they carry the run-id, bundle digest, env, secrets, and JSON
//!    input the backends need to actually launch a sandbox.
//!
//! The gRPC handler layer in `service.rs` is the bridge: it accepts
//! a wire-level `pb::SpawnRequest` and translates it into the
//! internal `ScheduleRequest` before calling into the backend.

use serde::{Deserialize, Serialize};

/// Generated tonic types — `lantern.v1` package from runtime.proto.
///
/// Server trait lives at `pb::runtime_manager_server::RuntimeManager`,
/// server struct at `pb::runtime_manager_server::RuntimeManagerServer`.
#[allow(
    clippy::enum_variant_names,
    clippy::large_enum_variant,
    clippy::doc_markdown,
    clippy::derive_partial_eq_without_eq
)]
pub mod pb {
    tonic::include_proto!("lantern.v1");
}

// ---------------------------------------------------------------------------
// Internal enums + types (consumed by backends, pool, registry)
// ---------------------------------------------------------------------------

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[repr(i32)]
pub enum IsolationClass {
    Unspecified = 0,
    Trusted = 1,
    Standard = 2,
    Untrusted = 3,
    Hostile = 4,
    Wasm = 5,
    Devcontainer = 6,
}

impl IsolationClass {
    pub fn from_i32(v: i32) -> Self {
        match v {
            1 => IsolationClass::Trusted,
            2 => IsolationClass::Standard,
            3 => IsolationClass::Untrusted,
            4 => IsolationClass::Hostile,
            5 => IsolationClass::Wasm,
            6 => IsolationClass::Devcontainer,
            _ => IsolationClass::Unspecified,
        }
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ResourceLimits {
    pub cpu: String,
    pub memory: String,
    pub gpu: String,
    pub timeout: String,
    pub max_steps: i64,
    pub max_tokens: i64,
    pub max_cost_usd: f64,
    pub scratch_size: String,
}

impl Default for ResourceLimits {
    fn default() -> Self {
        Self {
            cpu: "1".to_string(),
            memory: "512Mi".to_string(),
            gpu: String::new(),
            timeout: "300s".to_string(),
            max_steps: 100,
            max_tokens: 100_000,
            max_cost_usd: 1.0,
            scratch_size: "1Gi".to_string(),
        }
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SecretRef {
    pub alias: String,
    pub vault_ref: String,
    pub env_var: String,
}

/// Network egress policy class for a scheduled workload.
///
/// Mirrors `lantern.v1.NetworkPolicy` on the wire. The K8s Job backend maps
/// this (plus `egress_rules`) onto a Kubernetes `NetworkPolicy` object that is
/// default-deny with explicit allow rules.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize, Default)]
#[repr(i32)]
pub enum NetworkPolicyClass {
    #[default]
    Unspecified = 0,
    /// No egress at all (DNS still allowed so the pod can fail fast cleanly).
    None = 1,
    /// Domain/CIDR allowlist — default for untrusted workloads.
    AllowlistDomain = 2,
    /// Routable inside the tenant's namespace.
    TenantVpc = 3,
    /// Dangerous; trusted/wasm only. No K8s NetworkPolicy is emitted.
    Open = 4,
}

impl NetworkPolicyClass {
    pub fn from_i32(v: i32) -> Self {
        match v {
            1 => NetworkPolicyClass::None,
            2 => NetworkPolicyClass::AllowlistDomain,
            3 => NetworkPolicyClass::TenantVpc,
            4 => NetworkPolicyClass::Open,
            _ => NetworkPolicyClass::Unspecified,
        }
    }
}

/// A single egress allowlist entry. `pattern` is a domain (`*.openai.com`) or a
/// CIDR (`10.0.0.0/8`). The K8s NetworkPolicy backend can only express CIDR
/// peers natively (domain allowlisting is enforced in-VM by the harness), so
/// domain patterns are preserved here but only CIDR patterns become `ipBlock`
/// peers; domains rely on the DNS-allow rule plus the harness allowlist.
#[derive(Clone, Debug, Serialize, Deserialize, Default)]
pub struct EgressRule {
    pub pattern: String,
    #[serde(default)]
    pub http_methods: Vec<String>,
    #[serde(default)]
    pub rate_bps: i64,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ScheduleRequest {
    pub run_id: String,
    /// Authenticated tenant identity. Set by the gRPC handler from the
    /// wire-level `AgentSpec.tenant_id` (which the control-plane populates
    /// from the JWT). This is the authoritative source for tenant namespace
    /// derivation; it is never taken from the caller-supplied `env` map.
    pub tenant_id: String,
    pub bundle_uri: String,
    pub bundle_digest: Vec<u8>,
    pub isolation_class: IsolationClass,
    pub limits: ResourceLimits,
    pub env: std::collections::HashMap<String, String>,
    pub secrets: Vec<SecretRef>,
    pub input: serde_json::Value,
    /// Entrypoint override (empty = use image's ENTRYPOINT).
    #[serde(default)]
    pub command: Vec<String>,
    /// Arguments appended to entrypoint (or image CMD if command is empty).
    #[serde(default)]
    pub args: Vec<String>,
    /// Caller-supplied image. When non-empty the backend uses this instead
    /// of the manager's default `agent_image`. Headless agents always set
    /// this from `AgentSpec.image_digest` (the value should be a digest,
    /// `sha256:...`, or a fully-qualified image reference like
    /// `python:3.11-slim`).
    #[serde(default)]
    pub image: String,
    /// Egress policy class. The K8s Job backend translates this + `egress_rules`
    /// into a default-deny Kubernetes NetworkPolicy.
    #[serde(default)]
    pub network_policy: NetworkPolicyClass,
    /// Egress allowlist. CIDR patterns become `ipBlock` peers on the emitted
    /// NetworkPolicy; domain patterns are enforced in-VM by the harness.
    #[serde(default)]
    pub egress_rules: Vec<EgressRule>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ScheduleResponse {
    pub handle_id: String,
    pub node_name: String,
    pub cold_start_ms: f64,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct RuntimeCancelRequest {
    pub handle_id: String,
    pub reason: String,
    pub grace_period_seconds: i32,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct RuntimeCancelResponse {}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct RuntimeStreamRequest {
    pub handle_id: String,
}

// ---------------------------------------------------------------------------
// RuntimeEvent and its oneof variants
// ---------------------------------------------------------------------------

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StepRequest {
    pub step_id: String,
    pub kind: String,
    pub payload: serde_json::Value,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StepResponse {
    pub step_id: String,
    pub result: serde_json::Value,
    pub error: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct LlmRequest {
    pub step_id: String,
    pub capability: String,
    pub optimize: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct LlmDelta {
    pub step_id: String,
    pub delta: String,
    pub finish_reason: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct LogLine {
    pub level: String,
    pub message: String,
    pub timestamp: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct RuntimeExited {
    pub exit_code: i32,
    pub error: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum RuntimeEvent {
    StepRequest(StepRequest),
    StepResponse(StepResponse),
    LlmRequest(LlmRequest),
    LlmDelta(LlmDelta),
    Log(LogLine),
    ScreenFrame { data: Vec<u8> },
    Exited(RuntimeExited),
}

// ---------------------------------------------------------------------------
// Snapshot / Restore
// ---------------------------------------------------------------------------

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SnapshotRequest {
    pub handle_id: String,
    pub bundle_digest: Vec<u8>,
    pub isolation_class: IsolationClass,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SnapshotResponse {
    pub snapshot_uri: String,
    pub size_bytes: i64,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct RestoreRequest {
    pub snapshot_uri: String,
    pub run_id: String,
    /// Authenticated tenant identity — same invariant as `ScheduleRequest::tenant_id`.
    pub tenant_id: String,
    pub input: serde_json::Value,
    pub env: std::collections::HashMap<String, String>,
    pub secrets: Vec<SecretRef>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct RestoreResponse {
    pub handle_id: String,
    pub restore_ms: f64,
}
