// Agent catalog for the personal suite — verbatim data from apps/docs personal page.
// Used by the agent detail page to render the loop diagram + metadata for known agents.
// For user-created agents not in this map, the detail page renders nothing extra.

import type { AgentLoopProps } from "@/components/agent-loop";

export type CatalogEntry = Omit<AgentLoopProps, "title"> & {
  whatItDoes: string;
};

// ponytail: plain map, no class/factory needed
export const AGENT_CATALOG: Record<string, CatalogEntry> = {
  "concierge": {
    whatItDoes: "Captures tasks, researches how, nudges with 1-click actions — reply / snooze / done.",
    execModel: "scheduled",
    cadence: "~45m cron",
    stages: ["Capture task", "Research how", "Nudge you", "You act"],
    tone: "sky",
    ownerFacing: true,
    interface: "runs: ~45m · you see it: self-chat (reply / snooze / done)",
  },
  "care-coordinator": {
    whatItDoes: "Health email → meds/doctors/appts records + refill/appt reminders + coaching.",
    execModel: "scheduled",
    cadence: "daily 8am",
    stages: ["Morning scan", "Health records", "Refill/appt alert", "You act"],
    tone: "emerald",
    ownerFacing: true,
    interface: "runs: daily 8am · you see it: /personal Health · needs Gmail",
  },
  "garage": {
    whatItDoes: "Tesla + Odyssey service/insurance/DMV → records + renewal reminders.",
    execModel: "scheduled",
    cadence: "daily",
    stages: ["Gmail scan", "Vehicle records", "Renewal alert", "You act"],
    tone: "amber",
    ownerFacing: true,
    interface: "runs: daily · you see it: /personal Vehicle · needs Gmail",
  },
  "upskill": {
    whatItDoes: "Job/learning email → skill records + career coaching nudges.",
    execModel: "scheduled",
    cadence: "daily",
    stages: ["Gmail scan", "Skill records", "Career nudge", "You act"],
    tone: "violet",
    ownerFacing: true,
    interface: "runs: daily · you see it: /personal Career · needs Gmail",
  },
  "travel-concierge": {
    whatItDoes: "Flights/hotels → itinerary records + check-in reminders.",
    execModel: "scheduled",
    cadence: "daily",
    stages: ["Gmail scan", "Trip records", "Check-in alert", "You act"],
    tone: "sky",
    ownerFacing: true,
    interface: "runs: daily · you see it: /personal Travel · needs Gmail",
  },
  "household": {
    whatItDoes: "Utilities/warranties/services → records + renewal reminders.",
    execModel: "scheduled",
    cadence: "daily",
    stages: ["Gmail scan", "Home records", "Renewal alert", "You act"],
    tone: "amber",
    ownerFacing: true,
    interface: "runs: daily · you see it: /personal Home · needs Gmail",
  },
  "financial-sentinel": {
    whatItDoes: "Watches bills for price hikes → review reminders. Never moves money.",
    execModel: "scheduled",
    cadence: "daily",
    stages: ["Scan bills", "Detect price hike", "Flag for review", "You review"],
    tone: "amber",
    ownerFacing: true,
    interface: "runs: daily · you see it: /personal Finance · needs Gmail",
  },
  "relationship-keeper": {
    whatItDoes: "Finds people gone quiet (21d+) → reach-out reminders + draft in your voice.",
    execModel: "scheduled",
    cadence: "weekly",
    stages: ["Scan people", "Gone quiet?", "Draft in your voice", "Nudge you", "You reach out"],
    tone: "violet",
    ownerFacing: true,
    interface: "runs: weekly · you see it: self-chat",
  },
  "morning-brief": {
    whatItDoes: "Texts you ~3 bullets every weekday at 8am on what matters today.",
    execModel: "scheduled",
    cadence: "daily 8am",
    stages: ["8am trigger", "Gather context", "Compose 3 bullets", "Text you"],
    tone: "emerald",
    ownerFacing: true,
    interface: "runs: daily 8am weekdays · you see it: self-chat",
  },
  "inbox-concierge": {
    whatItDoes: "Reads your Gmail each morning and texts a 3-bucket digest.",
    execModel: "scheduled",
    cadence: "daily AM",
    stages: ["Morning trigger", "Read Gmail", "Sort 3 buckets", "Text digest"],
    tone: "sky",
    ownerFacing: true,
    interface: "runs: daily AM · you see it: self-chat · needs Gmail",
  },
  "commute-copilot": {
    whatItDoes: "Driving signal → hands-free task surface + parked recap.",
    execModel: "bridge",
    cadence: "bridge interval",
    stages: ["Drive signal", "Task surface", "Parked recap", "You act"],
    tone: "amber",
    ownerFacing: true,
    interface: "runs: bridge interval · you see it: self-chat · LANTERN_COMMUTE=on",
  },
  "energy-guardian": {
    whatItDoes: "Short sleep → offer to lighten the day's load.",
    execModel: "bridge",
    cadence: "bridge interval",
    stages: ["Sleep signal", "Assess energy", "Lighten day", "You act"],
    tone: "rose",
    ownerFacing: true,
    interface: "runs: bridge interval · you see it: self-chat · LANTERN_ENERGY=on",
  },
  "health-coach": {
    whatItDoes: "Steps/sleep/workout nudges toward a daily goal.",
    execModel: "bridge",
    cadence: "bridge interval",
    stages: ["Step/sleep data", "Track goal", "Nudge you", "You act"],
    tone: "emerald",
    ownerFacing: true,
    interface: "runs: bridge interval · you see it: self-chat · LANTERN_HEALTH=on",
  },
  "focus-guardian": {
    whatItDoes: "Holds non-urgent nudges during Focus mode, recaps after.",
    execModel: "bridge",
    cadence: "bridge interval",
    stages: ["Focus signal", "Hold nudges", "Focus ends", "Recap to you"],
    tone: "violet",
    ownerFacing: true,
    interface: "runs: bridge interval · you see it: self-chat · LANTERN_FOCUS=on",
  },
  "whatsapp-assistant": {
    whatItDoes: "Auto-replies to your WhatsApp contacts in your voice.",
    execModel: "reactive",
    cadence: "reactive",
    stages: ["Contact messages", "Understand", "Draft in your voice", "Send to contact"],
    tone: "rose",
    ownerFacing: false,
    interface: "fires: per inbound · you see it: replies to contacts",
  },
  "imessage-assistant": {
    whatItDoes: "Auto-replies to your iMessage contacts in your voice.",
    execModel: "reactive",
    cadence: "reactive",
    stages: ["Contact messages", "Understand", "Draft in your voice", "Send to contact"],
    tone: "rose",
    ownerFacing: false,
    interface: "fires: per inbound · you see it: replies to contacts",
  },
};
