// Demo fleet — a clearly-labeled, fabricated set of workloads + cluster
// capacity used to populate the Runtime Command Center when the live API
// returns no VMs (empty fleet) OR is unreachable (offline).
//
// HONESTY CONTRACT: this data is ONLY ever rendered behind a visible
// "Demo fleet" badge. Real VMs returned by /v1/runtime/vms are NEVER
// merged with or decorated by this. The animated CPU/mem/cost sparklines
// in the cockpit are simulated from `lib/runtime-metrics.ts` and are
// applied ONLY to rows flagged `demo: true`. A real VM with no metrics
// endpoint renders "—", never a fabricated curve. See page.tsx.

import type { VmRow, ClusterSummary } from "./runtime-types";

// Re-export so the page can import shapes + demo data from neighbors.
export type { VmRow, ClusterSummary } from "./runtime-types";

const now = Date.now();
const ago = (mins: number) => new Date(now - mins * 60_000).toISOString();
const secsAgo = (s: number) => new Date(now - s * 1000).toISOString();

// ~12 realistic workloads spanning every state, isolation tier, and region.
// `cpuBase` / `memBase` / `costHr` seed the simulated sparkline + cost rollup.
export const DEMO_VMS: VmRow[] = [
  {
    vmId: "vm_a1f93c7e2b4d8061",
    state: "running",
    name: "research-orchestrator",
    node: "node-iad-3",
    region: "us-east-1",
    az: "us-east-1a",
    isolationClass: "standard",
    createdAt: ago(412),
    lastHeartbeatAt: secsAgo(4),
    cpuBase: 0.62,
    memBase: 0.54,
    costHr: 0.184,
    spec: { image: "ghcr.io/lantern/agent-runner:v4", vcpus: 4, memory_mb: 8192, agent: "research-orchestrator" },
  },
  {
    vmId: "vm_5c8e0a17f9d3b2e4",
    state: "running",
    name: "web-scraper-batch",
    node: "node-iad-3",
    region: "us-east-1",
    az: "us-east-1a",
    isolationClass: "untrusted",
    createdAt: ago(88),
    lastHeartbeatAt: secsAgo(2),
    cpuBase: 0.81,
    memBase: 0.39,
    costHr: 0.092,
    spec: { image: "ghcr.io/lantern/scraper:v2", vcpus: 2, memory_mb: 4096, egress: "allowlist" },
  },
  {
    vmId: "vm_9d2f4b6a8c1e0537",
    state: "running",
    name: "pii-redactor",
    node: "node-iad-7",
    region: "us-east-1",
    az: "us-east-1b",
    isolationClass: "hostile",
    createdAt: ago(31),
    lastHeartbeatAt: secsAgo(6),
    cpuBase: 0.44,
    memBase: 0.71,
    costHr: 0.241,
    spec: { image: "ghcr.io/lantern/redactor:v1", vcpus: 4, memory_mb: 16384, runtime: "kata" },
  },
  {
    vmId: "vm_3b7c1e9f5a2d6480",
    state: "spawning",
    name: "ml-inference-llama",
    node: "node-sfo-1",
    region: "us-west-2",
    az: "us-west-2a",
    isolationClass: "standard",
    createdAt: secsAgo(11),
    lastHeartbeatAt: null,
    cpuBase: 0.12,
    memBase: 0.18,
    costHr: 0.412,
    spec: { image: "ghcr.io/lantern/llama-infer:v3", vcpus: 8, memory_mb: 32768, gpu: 1 },
  },
  {
    vmId: "vm_e0a4c8d2b6f19357",
    state: "running",
    name: "invoice-extractor",
    node: "node-sfo-1",
    region: "us-west-2",
    az: "us-west-2a",
    isolationClass: "untrusted",
    createdAt: ago(204),
    lastHeartbeatAt: secsAgo(3),
    cpuBase: 0.33,
    memBase: 0.29,
    costHr: 0.071,
    spec: { image: "ghcr.io/lantern/doc-extract:v2", vcpus: 2, memory_mb: 4096 },
  },
  {
    vmId: "vm_7f1d3b5a9c0e2846",
    state: "draining",
    name: "nightly-eval-suite",
    node: "node-sfo-1",
    region: "us-west-2",
    az: "us-west-2b",
    isolationClass: "trusted",
    createdAt: ago(57),
    lastHeartbeatAt: secsAgo(9),
    cpuBase: 0.21,
    memBase: 0.46,
    costHr: 0.058,
    spec: { image: "ghcr.io/lantern/eval-runner:v5", vcpus: 2, memory_mb: 8192 },
  },
  {
    vmId: "vm_2c6e8a0d4b1f9753",
    state: "running",
    name: "browser-automation",
    node: "node-iad-7",
    region: "us-east-1",
    az: "us-east-1b",
    isolationClass: "hostile",
    createdAt: ago(19),
    lastHeartbeatAt: secsAgo(1),
    cpuBase: 0.91,
    memBase: 0.83,
    costHr: 0.266,
    spec: { image: "ghcr.io/lantern/headless-chrome:v6", vcpus: 4, memory_mb: 16384, runtime: "kata" },
  },
  {
    vmId: "vm_b8d0f2a4c6e13579",
    state: "running",
    name: "wasm-policy-check",
    node: "node-iad-3",
    region: "us-east-1",
    az: "us-east-1a",
    isolationClass: "wasm",
    createdAt: ago(6),
    lastHeartbeatAt: secsAgo(5),
    cpuBase: 0.07,
    memBase: 0.09,
    costHr: 0.011,
    spec: { image: "ghcr.io/lantern/policy.wasm", runtime: "wasmtime" },
  },
  {
    vmId: "vm_4a9c1e3f7b5d0286",
    state: "failed",
    name: "etl-pipeline-sync",
    node: "node-iad-7",
    region: "us-east-1",
    az: "us-east-1b",
    isolationClass: "standard",
    createdAt: ago(143),
    terminatedAt: ago(138),
    lastHeartbeatAt: ago(140),
    cpuBase: 0,
    memBase: 0,
    costHr: 0,
    spec: { image: "ghcr.io/lantern/etl:v1", vcpus: 2, memory_mb: 4096, exit_code: 137 },
  },
  {
    vmId: "vm_d6f8b0a2c4e15937",
    state: "pending",
    name: "cost-forecaster",
    node: null,
    region: "us-west-2",
    az: null,
    isolationClass: "trusted",
    createdAt: secsAgo(4),
    lastHeartbeatAt: null,
    cpuBase: 0,
    memBase: 0,
    costHr: 0.034,
    spec: { image: "ghcr.io/lantern/forecaster:v2", vcpus: 1, memory_mb: 2048 },
  },
  {
    vmId: "vm_1e5c9a7f3b0d2648",
    state: "running",
    name: "devcontainer-shakes",
    node: "node-sfo-1",
    region: "us-west-2",
    az: "us-west-2a",
    isolationClass: "devcontainer",
    createdAt: ago(1340),
    lastHeartbeatAt: secsAgo(7),
    cpuBase: 0.18,
    memBase: 0.52,
    costHr: 0.121,
    spec: { image: "ghcr.io/lantern/devcontainer:base", vcpus: 4, memory_mb: 8192, persistent: true },
  },
  {
    vmId: "vm_8c0a2e4f6b9d1735",
    state: "terminated",
    name: "smoke-test-runner",
    node: "node-iad-3",
    region: "us-east-1",
    az: "us-east-1a",
    isolationClass: "trusted",
    createdAt: ago(95),
    terminatedAt: ago(92),
    lastHeartbeatAt: ago(93),
    cpuBase: 0,
    memBase: 0,
    costHr: 0,
    spec: { image: "alpine:latest", vcpus: 1, memory_mb: 1024 },
  },
];

export const DEMO_CLUSTER: ClusterSummary = {
  total_vms_running: DEMO_VMS.filter((v) => v.state === "running").length,
  total_vms_pending: DEMO_VMS.filter((v) => v.state === "pending" || v.state === "spawning").length,
  nodes: [
    {
      name: "node-iad-3",
      region: "us-east-1",
      availability_zone: "us-east-1a",
      running_vms: 4,
      free_vcpu_millis: 14_000, // 14 of 32 vCPU free
      free_memory_bytes: 38 * 1024 ** 3, // 38 of 128 GiB free
      total_vcpu_millis: 32_000,
      total_memory_bytes: 128 * 1024 ** 3,
      draining: false,
    },
    {
      name: "node-iad-7",
      region: "us-east-1",
      availability_zone: "us-east-1b",
      running_vms: 2,
      free_vcpu_millis: 6_000, // hot node — 6 of 32 free
      free_memory_bytes: 18 * 1024 ** 3,
      total_vcpu_millis: 32_000,
      total_memory_bytes: 128 * 1024 ** 3,
      draining: false,
    },
    {
      name: "node-sfo-1",
      region: "us-west-2",
      availability_zone: "us-west-2a",
      running_vms: 3,
      free_vcpu_millis: 22_000,
      free_memory_bytes: 70 * 1024 ** 3,
      total_vcpu_millis: 48_000,
      total_memory_bytes: 192 * 1024 ** 3,
      draining: false,
    },
  ],
  warm_pool: { available: 6, target: 8, regions: { "us-east-1": 4, "us-west-2": 2 } },
};
