import { agent, step } from "@lantern/sdk";

export default agent({
  name: "{{.Name}}",
  async run({ input, ctx }) {
    // Step 1: Search the web for information on the topic.
    const searchResults = await step("web-search", async () => {
      const results = await ctx.tools.webSearch({
        query: input.query,
        maxResults: 5,
      });

      ctx.log.info("Web search complete", { resultCount: results.length });

      return results.map((r: { title: string; url: string; snippet: string }) => ({
        title: r.title,
        url: r.url,
        snippet: r.snippet,
      }));
    });

    // Step 2: Run Python code to process and analyze the search results.
    const analysis = await step("python-analysis", async () => {
      const code = `
import json

results = json.loads('''${JSON.stringify(searchResults)}''')

# Extract key themes from snippets.
words = []
for r in results:
    words.extend(r["snippet"].lower().split())

# Simple word frequency analysis (excluding common stop words).
stop_words = {"the", "a", "an", "is", "are", "was", "were", "in", "on", "at", "to", "for", "of", "and", "or", "but", "with", "this", "that", "it"}
freq = {}
for w in words:
    w = w.strip(".,!?;:\"'()[]")
    if len(w) > 2 and w not in stop_words:
        freq[w] = freq.get(w, 0) + 1

top_terms = sorted(freq.items(), key=lambda x: -x[1])[:10]

print(json.dumps({
    "totalResults": len(results),
    "topTerms": [{"term": t[0], "count": t[1]} for t in top_terms],
}))
`;

      const result = await ctx.tools.pythonExec({ code });
      return JSON.parse(result.stdout);
    });

    // Step 3: Write a summary report to a file.
    const reportPath = await step("write-report", async () => {
      const report = [
        `# Research Report: ${input.query}`,
        "",
        "## Sources",
        ...searchResults.map(
          (r: { title: string; url: string }) => `- [${r.title}](${r.url})`,
        ),
        "",
        "## Key Terms",
        ...analysis.topTerms.map(
          (t: { term: string; count: number }) => `- **${t.term}** (mentioned ${t.count} times)`,
        ),
        "",
        `_Generated by ${ctx.agent.name}_`,
      ].join("\n");

      const filePath = `/workspace/report-${Date.now()}.md`;
      await ctx.tools.fileWrite({ path: filePath, content: report });

      ctx.log.info("Report written", { path: filePath });
      return filePath;
    });

    return {
      query: input.query,
      sourcesFound: searchResults.length,
      topTerms: analysis.topTerms,
      reportPath,
    };
  },
});
