apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lantern-dp.fullname" . }}-config
  labels:
    {{- include "lantern-dp.labels" . | nindent 4 }}
data:
  REDIS_URL: {{ include "lantern-dp.redisURL" . | quote }}
  S3_ENDPOINT: {{ include "lantern-dp.s3Endpoint" . | quote }}
  S3_BUCKET: {{ include "lantern-dp.s3Bucket" . | quote }}
  LOG_LEVEL: {{ .Values.global.logLevel | quote }}
  CONTROL_PLANE_ENDPOINT: {{ .Values.controlPlane.endpoint | quote }}
  TENANT_ID: {{ .Values.controlPlane.tenantId | quote }}
  {{- if .Values.minio.enabled }}
  AWS_ACCESS_KEY_ID: {{ .Values.minio.auth.rootUser | quote }}
  {{- else if .Values.minio.external.accessKeyId }}
  AWS_ACCESS_KEY_ID: {{ .Values.minio.external.accessKeyId | quote }}
  {{- end }}
