apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lantern-dp.fullname" . }}-secrets
  labels:
    {{- include "lantern-dp.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.secrets.postgresPassword | b64enc | quote }}
  minio-password: {{ .Values.secrets.minioPassword | b64enc | quote }}
  agent-token: {{ .Values.controlPlane.agentToken | b64enc | quote }}
