apiVersion: v1
kind: Service
metadata:
  name: {{ include "lantern-cp.fullname" . }}-scheduler
  labels:
    {{- include "lantern-cp.componentLabels" (dict "root" . "component" "scheduler") | nindent 4 }}
spec:
  type: {{ .Values.scheduler.service.type }}
  ports:
    - port: {{ .Values.scheduler.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "lantern-cp.componentSelectorLabels" (dict "root" . "component" "scheduler") | nindent 4 }}
