{{- if (gt (int .Values.controlPlane.replicas) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "lantern-cp.fullname" . }}-control-plane
  labels:
    {{- include "lantern-cp.componentLabels" (dict "root" . "component" "control-plane") | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "lantern-cp.componentSelectorLabels" (dict "root" . "component" "control-plane") | nindent 6 }}
{{- end }}
