apiVersion: v1
kind: Service
metadata:
  name: {{ include "lantern-dp.fullname" . }}-workflow-engine
  labels:
    {{- include "lantern-dp.componentLabels" (dict "root" . "component" "workflow-engine") | nindent 4 }}
spec:
  type: {{ .Values.workflowEngine.service.type }}
  ports:
    - port: {{ .Values.workflowEngine.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "lantern-dp.componentSelectorLabels" (dict "root" . "component" "workflow-engine") | nindent 4 }}
