"use client";

// <ViewCode /> — universal "show me the SDK equivalent" button.
//
// Drop it on any page that represents an API action; pass the action
// metadata and ViewCode emits Python / Go / TypeScript / cURL snippets
// the user can copy-paste into their own code.
//
// This is the OpenAI Platform "View code" pattern, generalized: every
// action you can take in the dashboard is also reachable from the SDKs
// — the snippet is a teaching moment, not a marketing gesture.

import { useState } from "react";
import { Code2, Copy, Check, X } from "lucide-react";
import clsx from "clsx";
import { useToast } from "@/components/toast";

type Lang = "ts" | "python" | "go" | "curl";

const LANG_LABEL: Record<Lang, string> = {
  ts: "TypeScript",
  python: "Python",
  go: "Go",
  curl: "cURL",
};

const LANG_ORDER: Lang[] = ["ts", "python", "go", "curl"];

// Snippets generated by the caller. Pass any subset; missing languages
// just don't render as tabs. The renderer expects raw source code —
// it'll syntax-highlight (well, monospace-format) it itself.
export interface ViewCodeSnippets {
  ts?: string;
  python?: string;
  go?: string;
  curl?: string;
}

interface ViewCodeProps {
  // Label for the button and modal title (e.g. "Get this run").
  title: string;
  snippets: ViewCodeSnippets;
  // Display variant for the trigger. "button" is the default, suitable
  // for the page-action area; "icon" is a 24x24 tile for cramped UIs.
  variant?: "button" | "icon";
  className?: string;
}

export function ViewCode({ title, snippets, variant = "button", className }: ViewCodeProps) {
  const toast = useToast();
  const [open, setOpen] = useState(false);
  const available = LANG_ORDER.filter((l) => snippets[l]);
  const [active, setActive] = useState<Lang>(available[0] ?? "ts");

  if (available.length === 0) return null;

  return (
    <>
      <button
        onClick={() => {
          setActive(available[0]);
          setOpen(true);
        }}
        className={clsx(
          variant === "icon"
            ? "rounded-md p-1.5 text-zinc-500 transition-colors hover:bg-surface-3 hover:text-zinc-300"
            : "inline-flex items-center gap-1.5 rounded-md border border-zinc-700 px-2.5 py-1 text-[11px] font-medium text-zinc-400 transition-colors hover:border-zinc-600 hover:bg-surface-3 hover:text-zinc-200",
          className
        )}
        title="View SDK code"
      >
        <Code2 className="h-3.5 w-3.5" />
        {variant === "button" && <span>View code</span>}
      </button>

      {open && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm"
          onClick={() => setOpen(false)}
        >
          <div
            className="w-full max-w-2xl rounded-xl border border-zinc-800 bg-surface-1 shadow-2xl"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="flex items-center justify-between border-b border-zinc-800 px-4 py-3">
              <h3 className="text-sm font-semibold text-zinc-100">{title}</h3>
              <button
                onClick={() => setOpen(false)}
                aria-label="Close"
                className="rounded p-1 text-zinc-500 hover:bg-surface-3 hover:text-zinc-300"
              >
                <X className="h-4 w-4" />
              </button>
            </div>

            <div className="flex items-center gap-1 border-b border-zinc-800 px-3 pt-2">
              {available.map((lang) => (
                <button
                  key={lang}
                  onClick={() => setActive(lang)}
                  className={clsx(
                    "rounded-t-md px-3 py-1.5 text-[11px] font-medium transition-colors",
                    active === lang
                      ? "bg-surface-0 text-zinc-100"
                      : "text-zinc-500 hover:text-zinc-300"
                  )}
                >
                  {LANG_LABEL[lang]}
                </button>
              ))}
            </div>

            <div className="relative bg-surface-0">
              <pre className="max-h-[60vh] overflow-auto px-4 py-3 font-mono text-[12px] leading-relaxed text-zinc-200">
                {snippets[active]}
              </pre>
              <button
                onClick={() => {
                  navigator.clipboard.writeText(snippets[active] ?? "");
                  toast.success(`${LANG_LABEL[active]} snippet copied`);
                }}
                className="absolute right-3 top-3 rounded-md border border-zinc-700 bg-surface-1 p-1.5 text-zinc-400 transition-colors hover:bg-surface-2 hover:text-zinc-100"
                title="Copy to clipboard"
              >
                <Copy className="h-3 w-3" />
              </button>
            </div>

            <div className="border-t border-zinc-800 px-4 py-2 text-[11px] text-zinc-500">
              <span>
                Install:&nbsp;
                <code className="font-mono text-zinc-400">
                  {active === "ts" && "npm i @lantern/sdk"}
                  {active === "python" && "pip install lantern-sdk"}
                  {active === "go" && "go get github.com/dshakes/lantern/packages/sdk-go"}
                  {active === "curl" && "—"}
                </code>
              </span>
            </div>
          </div>
        </div>
      )}
    </>
  );
}

// ---------------------------------------------------------------------------
// Snippet builders for the common run actions. Keep these here, not in
// individual pages, so the snippet style stays consistent across the app.
// ---------------------------------------------------------------------------

export function snippetsForGetRun(runId: string, apiBase = "http://localhost:8080"): ViewCodeSnippets {
  return {
    ts: `import { Lantern } from "@lantern/sdk";

const lantern = new Lantern({ apiKey: process.env.LANTERN_API_KEY });

const run = await lantern.runs.get("${runId}");
console.log(run.status, run.output);`,
    python: `from lantern_sdk import Lantern

lantern = Lantern(api_key="...")  # or set LANTERN_API_KEY env var

run = lantern.runs.get("${runId}")
print(run.status, run.output)`,
    go: `package main

import (
\t"context"
\t"fmt"

\tlantern "github.com/dshakes/lantern/packages/sdk-go"
)

func main() {
\tclient := lantern.New(lantern.WithAPIKey("..."))
\trun, err := client.Runs.Get(context.Background(), "${runId}")
\tif err != nil { panic(err) }
\tfmt.Println(run.Status, run.Output)
}`,
    curl: `curl -H "Authorization: Bearer $LANTERN_API_KEY" \\
  ${apiBase}/v1/runs/${runId}`,
  };
}

export function snippetsForCreateRun(agentName: string, apiBase = "http://localhost:8080"): ViewCodeSnippets {
  const inputJSON = `{"message": "your input here"}`;
  return {
    ts: `import { Lantern } from "@lantern/sdk";

const lantern = new Lantern({ apiKey: process.env.LANTERN_API_KEY });

const run = await lantern.runs.create({
  agentName: "${agentName}",
  input: ${inputJSON},
});
console.log("started:", run.id);`,
    python: `from lantern_sdk import Lantern

lantern = Lantern(api_key="...")

run = lantern.runs.create(
    agent_name="${agentName}",
    input=${inputJSON},
)
print("started:", run.id)`,
    go: `package main

import (
\t"context"
\t"fmt"

\tlantern "github.com/dshakes/lantern/packages/sdk-go"
)

func main() {
\tclient := lantern.New(lantern.WithAPIKey("..."))
\trun, err := client.Runs.Create(context.Background(), &lantern.CreateRunRequest{
\t\tAgentName: "${agentName}",
\t\tInput:     map[string]any{"message": "your input here"},
\t})
\tif err != nil { panic(err) }
\tfmt.Println("started:", run.ID)
}`,
    curl: `curl -X POST \\
  -H "Authorization: Bearer $LANTERN_API_KEY" \\
  -H "Content-Type: application/json" \\
  -d '{"agentName": "${agentName}", "input": ${inputJSON}}' \\
  ${apiBase}/v1/runs`,
  };
}

export function snippetsForSubmitFeedback(runId: string, apiBase = "http://localhost:8080"): ViewCodeSnippets {
  return {
    ts: `import { Lantern } from "@lantern/sdk";

const lantern = new Lantern({ apiKey: process.env.LANTERN_API_KEY });

await lantern.runs.feedback("${runId}", {
  score: 5,                 // 1-5
  comment: "nailed it",
  source: "sdk",
});`,
    python: `from lantern_sdk import Lantern

lantern = Lantern(api_key="...")
lantern.runs.feedback(
    run_id="${runId}",
    score=5,                 # 1-5
    comment="nailed it",
    source="sdk",
)`,
    curl: `curl -X POST \\
  -H "Authorization: Bearer $LANTERN_API_KEY" \\
  -H "Content-Type: application/json" \\
  -d '{"score":5,"comment":"nailed it","source":"sdk"}' \\
  ${apiBase}/v1/runs/${runId}/feedback`,
  };
}
